### ISSUE TITLE
Error message in paper 1.17.1

### ISSUE THREAD

**Issue by SeanWalk** [Rothes/ProtocolStringReplacer#2] opened 2021-07-12 00:28 UTC
**Describe the bug**
[16:04:02] [Server thread/ERROR]: [ProtocolStringReplacer] Unhandled exception occured in onPacketSending(PacketEvent) for ProtocolStringReplacer
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 34 path $.text
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.17.1.jar:git-Paper-99]
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:101) ~[patched_1.17.1.jar:git-Paper-99]
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:44) ~[patched_1.17.1.jar:git-Paper-99]
	at me.Rothes.ProtocolStringReplacer.PacketListeners.Server.Chat$1.onPacketSending(Chat.java:48) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:294) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:258) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1905) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1891) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:2188) ~[patched_1.17.1.jar:git-Paper-99]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:215) ~[patched_1.17.1.jar:git-Paper-99]
	at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:189) ~[patched_1.17.1.jar:git-Paper-99]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:831) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-99]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-99]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 34 path $.text
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[patched_1.17.1.jar:git-Paper-99]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[patched_1.17.1.jar:git-Paper-99]
	... 47 more
[16:04:02] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutChat@5258829c[
    a=<null>
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

**To Reproduce**
after upgrade PlaceholderAPI to 2.10.10 Protocollib to 4.7

**Expected behavior**
just error in console not really know what happen

**Server Informations**
 - Minecraft Version: paper-1.17.1-99
 - ProtocolLib Version: ProtocolLib v4.7
 - ProtocolStringReplacer Version: [e.g. 1.1.0-beta]
 -  Plugins (46): AntiCreeper, AutoSaveWorld*, BetterFarming, Boss, ChestProtect, Citizens, CleanMotD*, CMI, CMILib, ColdStorage, CoreProtect, CrashAPI, CustomRecipeAPI, DeepStoragePlus, DiceFurniture, DiscordSRV, dynmap, Elevator, FurnitureLib, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, ItemCreatorPlus, LagAssist, Lift, LightAPI, LimitPillagers, LoneLibs, LuckPerms, MultitoolPlusPro, Multiverse-Core, NashornPlus, PerWorldInventory, PlaceholderAPI, ProtectionLib, ProtocolLib, QuickShop, Residence, Shopkeepers, ShulkerPacks, TreasureChest, Vault, Vehicles, VillagerOptimiser, WorldBorder, WorldEdit

**Additional context**
Should i just type chinese here?

**Comment by Rothes** [comment] 2021-07-13 13:36
The problem has been confirmed and identified, will be fixed soon.

And it's ok to type Chinese here because it's still a Chinese only plugin...

**Comment by Rothes** [comment] 2021-07-14 05:02
A temporary fix is applied for this issue. But there are still some other things to do.
Please update your plugin, it should not occur again.

**Closed as completed** 2021-07-14 05:02 UTC
Labels: 🐞 Bug
